### ISSUE TITLE
Add voice channel status support.

### ISSUE THREAD

**Issue by ghost** [cop-discord/disfart#7]
Allow to edit and set the voice channel status, it's in the development build of discord.py but hasn't been released yet.

![image](https://github.com/cop-discord/disdick/assets/150133465/ddb05bf7-7cee-4ddd-a630-4f0afc2be159)

**Comment by ghost** [comment]
It won't appear when editing a voicechannel. I've had a look and it's in disdick but not discord v2.3

![image](https://github.com/cop-discord/disdick/assets/150133465/dae298c9-7f57-456d-9191-f3e43c23f951)

**Comment by populated** [comment]
> It won't appear when editing a voicechannel. I've had a look and it's in disdick but not discord v2.3
> 
> ![image](https://private-user-images.githubusercontent.com/150133465/324917735-dae298c9-7f57-456d-9191-f3e43c23f951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU4ODIsIm5iZiI6MTcxMzkwNTU4MiwicGF0aCI6Ii8xNTAxMzM0NjUvMzI0OTE3NzM1LWRhZTI5OGM5LTdmNTctNDU2ZC05MTkxLWYzZTQzYzIzZjk1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDUzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY4NjliZjk3ZTNiMWZhZGQzMGRjYzM4MzdkY2JlOTFmMzA1ZTk1ZWNjMTA4MzVjNDYwMzg3Y2YyNWJmOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Glozqfa6dtU_s3AvTyItVpU_-biAOYh0SfkLqLdvKrQ)

_Ah, you're wrong. Look closely at `discord (disdick)/channel.py` and go to `VoiceChannel`. The method `edit` does indeed support `status`, as stated in the docstrings. Just use `channel.edit(status="")`. I have already looked into this before, comparing both `disdick` and `discord.py`. `Disdick` 100% supports it._

And I stand corrected. It seems that nothing has been pushed to the actual library itself since last year (`2023-06-13T14:54:48`).

**Comment by populated** [comment]
If you wish to download the latest, you can simply do: `pip install git+https://github.com/cop-discord/disdick`

**Comment by ghost** [comment]
> > It won't appear when editing a voicechannel. I've had a look and it's in disdick but not discord v2.3
> > ![image](https://private-user-images.githubusercontent.com/150133465/324917735-dae298c9-7f57-456d-9191-f3e43c23f951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU4ODIsIm5iZiI6MTcxMzkwNTU4MiwicGF0aCI6Ii8xNTAxMzM0NjUvMzI0OTE3NzM1LWRhZTI5OGM5LTdmNTctNDU2ZC05MTkxLWYzZTQzYzIzZjk1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDUzMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGY4NjliZjk3ZTNiMWZhZGQzMGRjYzM4MzdkY2JlOTFmMzA1ZTk1ZWNjMTA4MzVjNDYwMzg3Y2YyNWJmOWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Glozqfa6dtU_s3AvTyItVpU_-biAOYh0SfkLqLdvKrQ)
> 
> _Ah, you're wrong. Look closely at `discord (disdick)/channel.py` and go to `VoiceChannel`. The method `edit` does indeed support `status`, as stated in the docstrings. Just use `channel.edit(status="")`. I have already looked into this before, comparing both `disdick` and `discord.py`. `Disdick` 100% supports it._
> 
> And I stand corrected. It seems that nothing has been pushed to the actual library itself since last year (`2023-06-13T14:54:48`).

thanks im just an idiot
